version: '3.4'

services:
  spidclient:
    image: spidclient
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./log/:/usr/src/app/log/
    command: ["node", "createidps.js"]
